// Generated by Selenium IDE

package pkg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://www.google.com/search?q=books&sca_esv=3e98302ba505d99d&source=hp&ei=0PznZe2dCZ6XnesPjP26cA&iflsig=ANes7DEAAAAAZegK4KEUgTvJd5YzvaPhJyZUz2-o78Zt&ved=0ahUKEwjtxfzK8d6EAxWeS2cHHYy-Dg4Q4dUDCBU&uact=5&oq=books&gs_lp=Egdnd3Mtd2l6IgVib29rczILEAAYgAQYsQMYgwEyCBAAGIAEGLEDMg4QLhiABBixAxiDARjUAjIIEAAYgAQYsQMyERAuGIAEGLEDGIMBGMcBGK8BMgUQABiABDIFEAAYgAQyCBAAGIAEGLEDMggQABiABBixAzIFEAAYgARIuRBQAFjmCnAAeACQAQCYAX6gAcsEqgEDMC41uAEDyAEA-AEBmAIFoAKMBcICDhAuGIAEGIoFGLEDGIMBwgILEC4YgAQYsQMYgwHCAgUQLhiABMICCBAuGIAEGLEDwgILEC4YgAQYxwEY0QPCAgsQABiABBixAxjJA8ICCxAAGIAEGIoFGJIDwgIIEAAYgAQYkgPCAg4QLhiABBixAxjHARjRA5gDAJIHAzAuNaAH8S4&sclient=gws-wiz");
    {
      WebElement element = driver.findElement(By.linkText("Google Search Help"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'rso\']/div[2]/div/div/div/div/div/span/a/h3")).click();
    driver.close();
  }
}
